#!/bin/sh

echo "Running docgenerator..."
python docgenerator.py
echo "Updating commit..."

git add documentation/tuners.md
git add documentation/graph_filters.md
git add documentation/measures.md
git add documentation/postprocessors.md
git add documentation/datasets.md