name: codecov
on: [push]

jobs:
  check-coverage:
    steps:
      # (Other steps go here)
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        run-on: ubuntu-latest
        with:
          token: '949e2725-bd88-4856-aecc-c98d5a3c3ac4'
          fail_ci_if_error: true